api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

router = routers.DefaultRouter()
router.register(r'ladders',views.LadderViewSet)
router.register(r'users',views.CustomUserViewSet)


urlpatterns = [
    path('profile', views.ProfileView.as_view(),name='profile'),
    path('',include(router.urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('laddercompetitie.urls')),
]

laddercompetitie/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (SignupView,
    LadderListView, LadderDetailView, LadderUpdateView, LadderCreateView, LadderDeleteView,
    LadderRegisterView, LadderDeregisterView,
    ChallengeListView, ChallengeCreateView, ChallengeUpdateView, ChallengeDeleteView)

urlpatterns = [

    # Login/logout
    # path('login/',LoginView.as_view()),
    # path('logout/',logout_view,name='logout'),
    path('users/signup/', SignupView.as_view(), name='signup'),
    path('users/', include('django.contrib.auth.urls')),
    #index
    path('', LadderListView.as_view(), name='ladder-list'),
    path('ladder/create/', LadderCreateView.as_view(), name='ladder-create'),
    path('ladder/<slug:slug>/', LadderDetailView.as_view(), name='ladder-detail'),
    path('ladder/<slug:slug>/edit', LadderUpdateView.as_view(), name='ladder-edit'),
    path('ladder/<slug:slug>/delete', LadderDeleteView.as_view(), name='ladder-delete'),
    path('ladder/<slug:slug>/register', LadderRegisterView.as_view(), name='ladder-register'),
    path('ladder/<slug:slug>/deregister', LadderDeregisterView.as_view(), name='ladder-deregister'),

    path('challenges/', ChallengeListView.as_view(), name='challenge-list'),
    path('challenges/create', ChallengeCreateView.as_view(), name='challenge-create'),
    path('challenges/<int:pk>/edit', ChallengeUpdateView.as_view(), name='challenge-edit'),
    path('challenges/<int:pk>/delete', ChallengeDeleteView.as_view(), name='challenge-delete'),


]

laddercompetitie/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField
from uuid import uuid4
import os

from .utils import get_unique_slug

from django.utils import timezone


class CustomUser(AbstractUser):
    is_staff = models.BooleanField(
        'administrator',
        default=False,
        help_text='Administratie rechten'
    )

    is_superuser = models.BooleanField(
        # This field is necessary for using ckeditor
        default=False,
    )

    voornaam = models.CharField(
        'voornaam',
        max_length=50,
        blank=True,
        null=True,
        editable=True
    )
    tussenvoegsel = models.CharField(
        'tussenvoegsel',
        max_length=50,
        blank=True,
        null=True,
        editable=True
    )
    achternaam = models.CharField(
        'achternaam',
        max_length=100,
        blank=True,
        null=True,
        editable=True
    )
    geslacht = models.CharField(
        'geslacht',
        max_length=1,
        blank=True,
        null=True,
        editable=True
    )
    geboortedatum = models.DateField(
        'geboortedatum',
        blank=True,
        null=True,
        editable=True
    )
    telefoonnummer = models.CharField(
        'telefoonnummer',
        max_length=15,
        blank=True,
        null=True,
        editable=True
    )

    USERNAME_FIELD  = 'username'

    def naam(self):
        naam = []
        if self.voornaam:
            naam.append(self.voornaam)
        else:
            naam.append(self.voorletters)
        if self.tussenvoegsel:
            naam.append(self.tussenvoegsel)

        naam.append(self.achternaam)

        return ' '.join(naam)
    naam.short_description = 'naam'

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'


class Ladder(models.Model):

    name = models.CharField(
        'naam',
        max_length=128,
    )
    slug = models.SlugField(max_length=50, unique=True, blank=False)

    created_at = models.DateField(default=timezone.now)

    members = models.ManyToManyField(
        CustomUser,
        through='Membership')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'name', 'slug')
        super().save(*args, **kwargs)


    def __str__(self):
        return self.name

class Membership(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    ladder = models.ForeignKey(Ladder, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)
    rank = models.IntegerField()

    class Meta:
        ordering = ('rank',)

    def __str__(self):
        return "{}{}, {}".format(self.rank,self.user,self.ladder)


class Challenge(models.Model):
    challenger = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="user_challenger")
    challenged = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="user_challenged")
    ladder = models.ForeignKey(Ladder, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    score = models.CharField(max_length=100,blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.challenger} vs {self.challenged}, {self.ladder}"

laddercompetitie/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Challenge

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field


class ChallengeCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['challenged'].queryset = CustomUser.objects.exclude(id=user.id)
    class Meta:
        model = Challenge
        fields = ['challenged','ladder',]


class CustomUserCreationForm(UserCreationForm):
    voornaam = forms.CharField(max_length=30, required=False, help_text='Optional.')
    tussenvoegsel = forms.CharField(max_length=30, required=False, help_text='Optional.')
    achternaam = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=75,required=True)

    class Meta:
        model = CustomUser
        fields = ('username','email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class LoginForm(forms.Form):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('login', 'login', css_class='col-xs-4 col-sm-4 col-md-4 col-lg-4'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-xs-4 col-sm-3 col-md-3 col-lg-3'
    helper.field_class = 'col-xs-8 sol-sm-5 col-md-5 col-lg-5'

    username = forms.CharField(
        label='Gebruikersnaam:',
        required=True
    )

    password = forms.CharField(
        label='Wachtwoord:',
        required=True,
        widget=forms.PasswordInput
    )

laddercompetitie/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import PermissionDenied

from datetime import datetime

from .models import Ladder, CustomUser, Membership, Challenge
from .forms import LoginForm

from django.urls import reverse_lazy, reverse, resolve
from django.views import generic
from .forms import CustomUserCreationForm, ChallengeCreateForm
from django.contrib import messages

from .utils import rank_shuffle
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import logging






class LadderListView(ListView):
    model = Ladder
    queryset = Ladder.objects.order_by('-created_at','-id')
    template_name = 'laddercompetitie/index.html'
    paginate_by = 6

class LadderDetailView(DetailView):
    model = Ladder
    template_name = "laddercompetitie/ladder_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        slug = self.kwargs["slug"]
        ladder = Ladder.objects.get(slug=slug)
        players = ladder.members.all().order_by('membership')

        context["players"] = players

        user = self.request.user

        if user.is_authenticated:
            registered = Membership.objects.filter(user=user,ladder=ladder).exists()
        else:
            registered = False

        context["registered"] = registered

        return context


class LadderCreateView(PermissionRequiredMixin, CreateView):
    model = Ladder
    fields = ["name",]
    template_name = 'laddercompetitie/ladder_create.html'

    permission_required = ('ladder.can_create')

    def get_success_url(self):
        return reverse('ladder-detail', kwargs={'slug': self.object.slug})

class LadderUpdateView(PermissionRequiredMixin, UpdateView):
    model = Ladder
    fields= ["name",]
    template_name = 'laddercompetitie/ladder_edit.html'

    permission_required = ('ladder.can_change')

    def get_success_url(self):
        return reverse('ladder-detail', kwargs={'slug': self.object.slug})

class LadderDeleteView(PermissionRequiredMixin, DeleteView):
    model = Ladder
    template_name = 'laddercompetitie/ladder_delete.html'
    success_url = reverse_lazy('ladder-list')

    permission_required = ('ladder.can_delete')

class LadderRegisterView(LoginRequiredMixin, View):
    template_name = "laddercompetitie/ladder_register.html"
    login_url = reverse_lazy('login')

    def get(self, *args, **kwargs):
        context = {"ladder":Ladder.objects.get(slug=self.kwargs["slug"])}
        return render(self.request,self.template_name, context)

    def post(self,*args,**kwargs):
        registered = Membership.objects.filter(user=self.request.user,ladder=Ladder.objects.get(slug=self.kwargs["slug"])).exists()
        if not registered:
            membership = Membership(
                user=self.request.user,
                ladder=Ladder.objects.get(slug=self.kwargs["slug"]),
                rank=self.assign_rank())
            membership.save()
            messages.add_message(self.request, messages.INFO, 'You are registered')
        else:
            messages.add_message(self.request, messages.INFO, 'Already registered')
        return redirect('ladder-detail',slug=self.kwargs["slug"])

    def assign_rank(self):
        ladder = Ladder.objects.get(slug=self.kwargs["slug"])
        players = ladder.members.all()

        worst_rank = 0
        for player in players:
            rank = Membership.objects.get(ladder=ladder, user=player).rank
            if rank >= worst_rank:
                worst_rank = rank
        return worst_rank + 1


class LadderDeregisterView(LoginRequiredMixin, View):
    template_name="laddercompetitie/ladder_deregister.html"

    def get(self, *args, **kwargs):
        context = {"ladder":Ladder.objects.get(slug=self.kwargs["slug"])}
        return render(self.request,self.template_name, context)

    def post(self, *args, **kwargs):
        registered = Membership.objects.filter(user=self.request.user,ladder=Ladder.objects.get(slug=self.kwargs["slug"])).exists()
        if registered:
            slug = slug=self.kwargs["slug"]
            ladder = Ladder.objects.get(slug=slug)
            user=self.request.user
            user.membership_set.get(ladder=ladder).delete()
            messages.add_message(self.request, messages.INFO, 'successfully deregistered')
            rank_shuffle(ladder)
        else:
            messages.add_message(self.request, messages.INFO, 'Not registered')
        return redirect('ladder-detail',slug=slug)

class ChallengeListView(LoginRequiredMixin, ListView):
    template_name="laddercompetitie/challenge_list.html"
    model=Challenge

    def get_queryset(self):
        q1 = Challenge.objects.filter(challenger=self.request.user)
        q2 = Challenge.objects.filter(challenged=self.request.user)
        return q1.union(q2).order_by('accepted')

class ChallengeCreateView(LoginRequiredMixin, CreateView):
    model = Challenge
    #fields = ["challenged","ladder"]
    template_name = 'laddercompetitie/challenge_create.html'
    success_url = reverse_lazy('challenge-list')
    form_class = ChallengeCreateForm

    def form_valid(self, form):
        challenger = CustomUser.objects.get(pk=self.request.user.pk)
        form.instance.challenger = challenger
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class ChallengeUpdateView(LoginRequiredMixin, UpdateView):
    model = Challenge
    template_name = 'laddercompetitie/challenge_edit.html'
    success_url = reverse_lazy('challenge-list')
    fields = ["accepted",]

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        if object.challenged != self.request.user:
            raise PermissionDenied()

        if object.accepted:
            raise PermissionDenied()

        return object



class ChallengeDeleteView(LoginRequiredMixin, DeleteView):
    model = Challenge
    template_name = 'laddercompetitie/challenge_delete.html'
    success_url = reverse_lazy('challenge-list')

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        if object.challenged != self.request.user and object.challenger != self.request.user:
            raise PermissionDenied()
        return object




class SignupView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'



# class LoginView(View):
#     def get(self, request, *args, **kwargs):
#         context = {
#             'loginform': LoginForm(),
#         }
#         return render(request, 'laddercompetitie/login.html', context)
#
#     def post(self, request, *args, **kwargs):
#         loginform = LoginForm(request.POST)
#
#         if loginform.is_valid():
#             username = loginform.cleaned_data['username']
#             password = loginform.cleaned_data['password']
#             user = authenticate(request,username=username,password=password)
#
#             if user is not None:
#                 # Succesfull login
#                 login(request,user)
#                 return redirect('/')
#             else:
#                 error_message = 'Username and/or password incorrect!'
#         else:
#             error_message = 'Invalid form!'
#
#         context = {
#             'loginform': loginform,
#             'error_message': error_message,
#         }
#         return render(request, 'app/login.html', context)
#
#
# def logout_view(request):
#     logout(request)
#     return redirect('/')

laddercompetitie/templates/laddercompetitie/base.html
<body>
    <div class="page-header">
        <h1><a href="/">LadderCompetitie</a></h1>
        <a href="/admin">admin</a>
        {%if user.is_authenticated%}
        <h4>Logged in as {{user}} <a href="{%url 'logout'%}">logout</a></h4>
        {%else%}
        <a href="{%url 'login'%}">login</a>
        {%endif%}
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

laddercompetitie/templates/laddercompetitie/challenge_create.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

laddercompetitie/templates/laddercompetitie/challenge_delete.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ challenge }}"?</p>
    <input type="submit" value="Confirm">
</form>


{% endblock %}

laddercompetitie/templates/laddercompetitie/challenge_edit.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

laddercompetitie/templates/laddercompetitie/challenge_list.html
{% extends 'laddercompetitie/base.html' %}
{% load static %}

{% block content %}
    <h1>Challenges</h1>

    <h2><a href="{% url 'challenge-create' %}">create new challenge</a></h2>

    <ul>
    {% for challenge in challenge_list %}

        <li>
          {{ challenge }}
          {% if challenge.accepted %}
            &#10004
          {% else %}
            &#10007;
          {% endif %}
          <a href="{% url 'challenge-edit' challenge.pk%}">edit</a>
          <a href="{% url 'challenge-delete' challenge.pk%}">delete</a>
        </li>

    {% endfor %}
    </ul>

{% endblock %}

laddercompetitie/templates/laddercompetitie/index.html
{% extends 'laddercompetitie/base.html' %}
{% load static %}

{% block content %}
    <h1>Ladders</h1>
    {% if user.is_superuser %}
    <h2><a href="{% url 'ladder-create' %}"> New ladder</a></h2>
    {% endif %}

    </div>
    <ul>
    {% for ladder in ladder_list %}

        <li>
          <a href="{% url 'ladder-detail' ladder.slug %}">{{ ladder.name }}</a>
        </li>

    {% endfor %}
    </ul>

    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <h2><a href="{% url 'challenge-list'%}">Challenges</a></h2>
      <p><a href="{% url 'logout' %}">logout</a></p>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">login</a> |
      <a href="{% url 'signup' %}">signup</a>
    {% endif %}

{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_create.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_delete.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ ladder }}"?</p>
    <input type="submit" value="Confirm">
</form>


{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_deregister.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}
  <p>Are you sure you want to deregister for "{{ ladder }}"?</p>

  <form method="post">{% csrf_token %}
      <input type="submit" value="Deregister">
  </form>




{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_detail.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}
{% load app_filters %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if user.is_superuser %}
<h3><a href="{% url 'ladder-edit' ladder.slug %}"> Edit ladder</a></h3>
<h3><a href="{% url 'ladder-delete' ladder.slug %}"> Delete ladder</a></h3>
{% endif %}
  <h1>{{ ladder.name }}</h1>

  {% if not registered %}
  <h2><a href="{% url 'ladder-register' ladder.slug %}">Register</a></h2>
  {% else %}
  <h2><a href="{% url 'ladder-deregister' ladder.slug %}">Deregister</a></h2>
  {% endif %}

  <ul>
      {%for player in players%}
        <li>{{player|rank:ladder}} {{player}}</li>
      {% empty %}
        <h3>No registered players</h3>
      {% endfor %}

  </ul>




{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_edit.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

laddercompetitie/templates/laddercompetitie/ladder_register.html
{% extends 'laddercompetitie/base.html' %}

{% block content %}
  <p>Are you sure you want to register for "{{ ladder }}"?</p>

  <form method="post">{% csrf_token %}
      <input type="submit" value="Register">
  </form>


{% endblock %}